channels:
- pyviz

packages:
- jupyter-panel-proxy
- panel
- pip==21.3.1
pip:
- pandas==1.2.3
- langchain==0.0.18
- openai
- # geogif
- fire
- psycopg2-binary
- rasterio
- # stackstac
- odc-stac
- botocore
- odc-algo
- psycopg2
- rasterio
- rioxarray
- spyndex
- xarray_leaflet